//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionCriteria
    {
        public int ID { get; set; }
        public string SessionStartDate { get; set; }
        public string DateOfNotice { get; set; }
        public string LastDateOfReciept { get; set; }
        public Nullable<int> NumberOfApplication { get; set; }
        public string DateOfAdmissionCompleted { get; set; }
        public string CriteriaForAddmision { get; set; }
        public string IsTraineeQualified { get; set; }
        public string IsCopyEnclosed { get; set; }
        public string CCE { get; set; }
    }
}
