//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int ID { get; set; }
        public Nullable<int> No_Passout { get; set; }
        public Nullable<int> ntcIssued { get; set; }
        public Nullable<int> toIssued { get; set; }
    }
}
