//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfInsp { get; set; }
        public string PurposeOfInsp { get; set; }
        public string InspectorName { get; set; }
        public string InspectorDesg { get; set; }
        public string InspectorAdrs { get; set; }
        public string Report { get; set; }
    }
}
