//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITIDataEntities : DbContext
    {
        public ITIDataEntities()
            : base("name=ITIDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acheivement> Acheivements { get; set; }
        public virtual DbSet<AdmissionCriteria> AdmissionCriterias { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<ImageGallery> ImageGalleries { get; set; }
        public virtual DbSet<InspectionDetail> InspectionDetails { get; set; }
        public virtual DbSet<InstituteDetail> InstituteDetails { get; set; }
        public virtual DbSet<ITIResult> ITIResults { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<NewsTable> NewsTables { get; set; }
        public virtual DbSet<PlacementTable> PlacementTables { get; set; }
        public virtual DbSet<ResultList> ResultLists { get; set; }
        public virtual DbSet<StaffAttendence> StaffAttendences { get; set; }
        public virtual DbSet<StaffTable> StaffTables { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TarineeList> TarineeLists { get; set; }
        public virtual DbSet<TradeAffiliated> TradeAffiliateds { get; set; }
        public virtual DbSet<TradeAffiliationSou> TradeAffiliationSous { get; set; }
        public virtual DbSet<TradeAttendence> TradeAttendences { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
