//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITIResult
    {
        public int ID { get; set; }
        public Nullable<int> TotalStudent { get; set; }
        public Nullable<int> TotalAppeared { get; set; }
        public Nullable<int> Passout { get; set; }
        public Nullable<int> CertificateIssued { get; set; }
        public string Trade { get; set; }
        public string Session { get; set; }
    }
}
