//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<int> Practical { get; set; }
        public Nullable<int> Theory { get; set; }
        public Nullable<int> Ws_cal_science { get; set; }
        public Nullable<int> Attendence { get; set; }
        public Nullable<int> Eng_Drawing { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Month_Quarter { get; set; }
        public string Trade { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Sd_id { get; set; }
    }
}
