//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacementTable
    {
        public int ID { get; set; }
        public string Roll_No { get; set; }
        public string Name { get; set; }
        public string Trade { get; set; }
        public string PassingYear { get; set; }
        public string Org_Name { get; set; }
        public Nullable<int> SalaryOnJoin { get; set; }
    }
}
