//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultList
    {
        public int ID { get; set; }
        public string Trade { get; set; }
        public Nullable<System.DateTime> YearOfAlTT { get; set; }
        public Nullable<int> TraineesAppeared { get; set; }
        public Nullable<int> TraineesPassed { get; set; }
        public Nullable<int> Certificates { get; set; }
        public Nullable<int> TraineesJob { get; set; }
    }
}
