//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string StaffName { get; set; }
        public string FatherName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<int> Salary { get; set; }
        public string PanNumber { get; set; }
        public Nullable<int> AadharNumber { get; set; }
        public string Experience { get; set; }
        public string StaffType { get; set; }
        public string TeachSubFirst { get; set; }
        public string TeachSubSecond { get; set; }
        public string Subject { get; set; }
        public string SubjectNumFirst { get; set; }
        public string SubjectNumSecond { get; set; }
    }
}
