//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable
    {
        public int ID { get; set; }
        public string Designation { get; set; }
        public string Name { get; set; }
        public string Staff { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SchoolMatric { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Salary { get; set; }
        public string ACDetails { get; set; }
        public string PhotoGraph { get; set; }
    }
}
