//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string EnrollNo { get; set; }
        public string Category { get; set; }
        public string Trade { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Session { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> DateofAddmission { get; set; }
    }
}
