//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarineeList
    {
        public int ID { get; set; }
        public string Trade { get; set; }
        public Nullable<int> UnitFirst { get; set; }
        public Nullable<int> UnitSecond { get; set; }
        public Nullable<int> UnitThird { get; set; }
        public Nullable<int> TraineesFirst { get; set; }
        public Nullable<int> TraineesSecond { get; set; }
        public Nullable<int> TraineesThird { get; set; }
        public Nullable<int> InspectionFirst { get; set; }
        public Nullable<int> InspectionSecond { get; set; }
        public Nullable<int> InspectionThird { get; set; }
        public string AverageInspection { get; set; }
    }
}
