//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeAffiliationSou
    {
        public int ID { get; set; }
        public string TradeName { get; set; }
        public Nullable<int> FirstUnit { get; set; }
        public Nullable<int> SecondUnit { get; set; }
        public Nullable<int> ThirdUnit { get; set; }
        public string SessionYear { get; set; }
    }
}
