//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeAttendence
    {
        public int ID { get; set; }
        public string Trade { get; set; }
        public Nullable<int> NU_1 { get; set; }
        public Nullable<int> NU_2 { get; set; }
        public Nullable<int> NU_3 { get; set; }
        public Nullable<int> NT_onRoll_1 { get; set; }
        public Nullable<int> NT_onRoll_2 { get; set; }
        public Nullable<int> NT_onRoll_3 { get; set; }
        public Nullable<int> NT_Avail_1 { get; set; }
        public Nullable<int> NT_Avail_2 { get; set; }
        public Nullable<int> NT_Avail_3 { get; set; }
        public Nullable<decimal> Av_Att_1 { get; set; }
    }
}
