//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long ID { get; set; }
        public string DocName { get; set; }
        public string DocUrl { get; set; }
        public string DocDescription { get; set; }
    }
}
