//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MgttcEntities : DbContext
    {
        public MgttcEntities()
            : base("name=MgttcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageGallery> ImageGalleries { get; set; }
        public virtual DbSet<InstituteDetail> InstituteDetails { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<NewsTable> NewsTables { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<DocCategory> DocCategories { get; set; }
        public virtual DbSet<DocCategoryImage> DocCategoryImages { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    }
}
