//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTable
    {
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string NewsHeadLine { get; set; }
        public string NewsText { get; set; }
        public int ID { get; set; }
    }
}
