//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhotoGraph { get; set; }
        public string Category { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> B_Ed_Marks { get; set; }
        public Nullable<decimal> M_Ed_Marks { get; set; }
        public Nullable<decimal> MA_Marks { get; set; }
        public Nullable<decimal> Masters_Marks { get; set; }
        public string TeachingSubject { get; set; }
        public Nullable<bool> Has_Phed { get; set; }
        public Nullable<bool> Has_UGC_Net { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public string Department { get; set; }
        public string StaffType { get; set; }
    }
}
