//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Category { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DateOfAdmit { get; set; }
        public string Session { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Ptet_Per { get; set; }
    }
}
